#!/usr/local/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.
// Especially useful for text-to-speech (both native and foreign).

let request = require("request");
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

request(url, function(error, response, body) {
  // Simulate a Document Object Model.
  const { document } = (new JSDOM(body)).window;

  // Grab all the paragraphs and references.
  let paragraphs = document.querySelectorAll("p");
  let references = document.querySelectorAll(".reference")

  // Remove any references.
  references.forEach(function(reference) {
    reference.remove();
  })

  // Print out all the paragraphs.
  paragraphs.forEach(function(paragraph) {
    console.log(paragraph.textContent + "\n");
  })
});
